name: Baggy Store ci/cd pipeline
on:
  push:
    branches:
      - dev

jobs:
  test:
    name: build application
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name : setup node
        uses : actions/setup-node@v2
        with :
          node-version: '18'
      - run : npm install
      - run : npm run build

  build:
    name: build and deploy to docker
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: checkout of repository
        uses: actions/checkout@v2
      - name: setup node version
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: login to docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/{{ APP_NAME }}:latest

  deploy:
    name: deploy to vercel
    runs-on : ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Deploy to Vercel
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{
              "name": "Baggy stores",
              "gitSource": {
                "type": "github",
                "ref": "${{ github.ref }}",
                "repo": "${{ github.repository }}"
              },
              "target": "production"
            }' \
            https://api.vercel.com/v1/deployments
